Name,JiraTicket__c,Description
ZOPA-4,https://pexlify.atlassian.net/browse/ZOPA-4,Create manual underwriting cases
ZOPA-7,https://pexlify.atlassian.net/browse/ZOPA-7,Pending button on manual underwriting cases
ZOPA-9,https://pexlify.atlassian.net/browse/ZOPA-9,Tasks sections on the manual underwriting cases
ZOPA-10,https://pexlify.atlassian.net/browse/ZOPA-10,Move to underwriters button on manual underwriting cases
ZOPA-11,https://pexlify.atlassian.net/browse/ZOPA-11,Send manual reminder button on manual underwriting cases
ZOPA-14,https://pexlify.atlassian.net/browse/ZOPA-14,Move case from pending queue on customer reply
ZOPA-15,https://pexlify.atlassian.net/browse/ZOPA-15,Block users from moving tasks without doing any tasks
ZOPA-16,https://pexlify.atlassian.net/browse/ZOPA-16,Omni channel queue
ZOPA-17,https://pexlify.atlassian.net/browse/ZOPA-17,Users cant do anything once a case is closed
ZOPA-18,https://pexlify.atlassian.net/browse/ZOPA-18,Configure referral codes and tasks
ZOPA-19,https://pexlify.atlassian.net/browse/ZOPA-19,Underwriter approve
ZOPA-20,https://pexlify.atlassian.net/browse/ZOPA-20,Move case back to case prep
ZOPA-21,https://pexlify.atlassian.net/browse/ZOPA-21,Move case to fraud
ZOPA-22,https://pexlify.atlassian.net/browse/ZOPA-22,Move case back to underwriter
ZOPA-23,https://pexlify.atlassian.net/browse/ZOPA-23,Record the initial underwriter
ZOPA-29,https://pexlify.atlassian.net/browse/ZOPA-29,Cancel loan application
ZOPA-34,https://pexlify.atlassian.net/browse/ZOPA-34,Decline loan application
ZOPA-35,https://pexlify.atlassian.net/browse/ZOPA-35,Make a loan quick pay
ZOPA-36,https://pexlify.atlassian.net/browse/ZOPA-36,Approve a loan and make free quick pay
ZOPA-37,https://pexlify.atlassian.net/browse/ZOPA-37,Admin bulk approve loan applications
ZOPA-48,https://pexlify.atlassian.net/browse/ZOPA-48,Automatically cancel loan applications
ZOPA-54,https://pexlify.atlassian.net/browse/ZOPA-54,View loan application documents
ZOPA-55,https://pexlify.atlassian.net/browse/ZOPA-55,Upload a document
ZOPA-57,https://pexlify.atlassian.net/browse/ZOPA-57,View bank details
ZOPA-58,https://pexlify.atlassian.net/browse/ZOPA-58,Classify document
ZOPA-59,https://pexlify.atlassian.net/browse/ZOPA-59,Notify Zopa on manual underwriting case pickup
ZOPA-72,https://pexlify.atlassian.net/browse/ZOPA-72,Notify user when customer uploads documents online
ZOPA-73,https://pexlify.atlassian.net/browse/ZOPA-73,View employment details
ZOPA-74,https://pexlify.atlassian.net/browse/ZOPA-74,View payment history
ZOPA-76,https://pexlify.atlassian.net/browse/ZOPA-76,View CIFA information
ZOPA-77,https://pexlify.atlassian.net/browse/ZOPA-77,View CCJ information
ZOPA-78,https://pexlify.atlassian.net/browse/ZOPA-78,View affordability information
ZOPA-79,https://pexlify.atlassian.net/browse/ZOPA-79,Update affordability information
ZOPA-80,https://pexlify.atlassian.net/browse/ZOPA-80,View bureau information
ZOPA-81,https://pexlify.atlassian.net/browse/ZOPA-81,Loan consolidation process
ZOPA-82,https://pexlify.atlassian.net/browse/ZOPA-82,Close manual underwriting case if loan application status changes
ZOPA-83,https://pexlify.atlassian.net/browse/ZOPA-83,View address details
ZOPA-89,https://pexlify.atlassian.net/browse/ZOPA-89,Log tasks for every action a user does
ZOPA-130,https://pexlify.atlassian.net/browse/ZOPA-130,Send case via assignment rules when loan is updated
ZOPA-147,https://pexlify.atlassian.net/browse/ZOPA-147,View the phone number match and electoral roll section on the loan page
ZOPA-156,https://pexlify.atlassian.net/browse/ZOPA-156,Validate bank details button on LoanPage - Bank Details section
ZOPA-166,https://pexlify.atlassian.net/browse/ZOPA-166,Create tasks for manual underwriting cases on change of owner or status
ZOPA-180,https://pexlify.atlassian.net/browse/ZOPA-180,Take MU case our of the queues if picked up in the admin system
ZCP-80,https://pexlify.atlassian.net/browse/ZOPA-80,Moving cases to Collections and Pre Arrears
ZCP-74,https://pexlify.atlassian.net/browse/ZCP-74,Omni channel queue for Collections Case
ZCP-55,https://pexlify.atlassian.net/browse/ZCP-55,Loan details
ZCP-56,https://pexlify.atlassian.net/browse/ZCP-56,Loan page bank detail information
ZCP-58,https://pexlify.atlassian.net/browse/ZCP-58,Promise to Pay send to BE
ZCP-71,https://pexlify.atlassian.net/browse/ZCP-76,Missed payment functionality
ZCP-76,https://pexlify.atlassian.net/browse/ZCP-76,Update Case sub-status to Pre-Default
ZCP-20,https://pexlify.atlassian.net/browse/ZCP-20,Loan payment history
ZCP-60,https://pexlify.atlassian.net/browse/ZCP-60,Loan litigation details
ZCP-61,https://pexlify.atlassian.net/browse/ZCP-61,Loan litigation details edit
ZCP-105,https://pexlify.atlassian.net/browse/ZCP-105,Change loan ststus to Rialto to deceased
ZCP-104,https://pexlify.atlassian.net/browse/ZCP-104,Changes in Loan fields and logic based on Loan_event to ArrearsRatio
ZCP-106,https://pexlify.atlassian.net/browse/ZCP-106,Set loan towithdrawn
ZCP-107,https://pexlify.atlassian.net/browse/ZCP-107,Change loan ststus to Rialto to deceased
ZS-44,https://pexlify.atlassian.net/browse/ZS-44,EmailAttachments sends to backend
ZCP-128,https://pexlify.atlassian.net/browse/ZCP-128,Linking Loan to Account on create Loan
ZCP-135,https://pexlify.atlassian.net/browse/ZCP-135,Make Loan and Case DCA lookups always the same
ZCP-157,https://pexlify.atlassian.net/browse/ZCP-157,When arrears ratio gets to 4 the loan should move to sub process Pre Default
ZCP-149,https://pexlify.atlassian.net/browse/ZCP-149,Create the related tasks and chatter posts after the loan state changes
ZCP-143,https://pexlify.atlassian.net/browse/ZCP-143,Added another radio button option named 'Pay Now'
ZCP-160,https://pexlify.atlassian.net/browse/ZCP-160,Show message when repayments list is empty
ZCP-98,https://pexlify.atlassian.net/browse/ZCP-98,Added Collections Notes to a loan end functionality to edit it on view loan page
ZCP-24,https://pexlify.atlassian.net/browse/ZCP-24,Added Manage Payment Plan feature
ZCP-122,https://pexlify.atlassian.net/browse/ZCP-122,Loan Notes Block
ZCP-169,https://pexlify.atlassian.net/browse/ZCP-169,Added Pay Now link to the loan view
ZCP-195,https://pexlify.atlassian.net/browse/ZCP-195,DCA link on Case and Loan should removed when Arrears ration is equals or more than 4
ZCP-123,https://pexlify.atlassian.net/browse/ZCP-123,Assign and Unassign button on Loan and Case Pages
ZCP-212,https://pexlify.atlassian.net/browse/ZCP-212,Fix prod errors on LoanApp and Case pages
ZCP-78,https://pexlify.atlassian.net/browse/ZCP-78,Account View page override based on FS and account record type
ZCP-189,https://pexlify.atlassian.net/browse/ZCP-189,Changed NextChaseCallDate to NextReviewDate and added StopCommunicationUntil
ZS-34,https://pexlify.atlassian.net/browse/ZS-34,Assign closed Case to Data Importer